### ISSUE TITLE
Support more than 9 choices

### ISSUE THREAD

**Issue by sefsh** [YingzhouLi/smartpoll#1]
Excellent plugin! Sometimes though I need votes for 9+ choices, in which smartpoll stops being useful. I suggest that the numbered list and corresponding reply emojis in such voting rounds are replaced by random emojis, as is the case in [TomCasavant/PollMaubot](https://github.com/TomCasavant/PollMaubot/) (perhaps use a subset of emojis that has no 👎, 🚫 etc such as the animal and food emoji sections)

**Comment by YingzhouLi** [comment]
The previous code supports 10 different choices. Now I have extend it to 26 choices. Voting for more than 26 choices is very rare. I hope this is good to you.

**Comment by sefsh** [comment]
Very nice. Thank you, I’ll try it out.

**Comment by sefsh** [comment]
The feature works, but only ever 10 letter emojis reactions are created.

<img width="551" alt="bild" src="https://user-images.githubusercontent.com/346211/163196877-8a06acc3-ae1a-4ae7-8d8f-7199fee002de.png">

**Comment by YingzhouLi** [comment]
What platform are you using? I am using Element version: 1.10.9, Olm version: 3.2.8 on my desktop and Element for Android on my phone. I cannot reproduce your issue.

**Comment by sefsh** [comment]
I’ll investigate. One thing I know is that my synapse is not the latest.
